In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
from nltk.tokenize import word_tokenize
import pandas as pd
import numpy as np
import re

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/S7/Text Mining/Exp 3/BBC News.csv")
df.head()

   ArticleId                                               Text
0       1833  worldcom ex-boss launches defence lawyers defe...
1        154  german business confidence slides german busin...
2       1101  bbc poll indicates economic gloom citizens in ...
3       1976  lifestyle  governs mobile choice  faster  bett...
4        917  enron bosses in $168m payout eighteen former e...

In [ ]:
#Word Tokenization
data = [i for i in df.iloc[:,1]]
df_word = []
for j in range(len(data)):
    df_word.append(word_tokenize(data[j]))

In [ ]:
len(df_word[9])

258

In [ ]:
# Removing Stopwords
from nltk.corpus import stopwords
stop_words=set(stopwords.words("english"))


#print(df_word[0:1]);
for i in range(len(df_word)):
    temp = []
    for j in df_word[i]:
        if j not in stop_words:
            temp.append(j)
    #print(temp)
    df_word[i] = temp.copy()

#print(df_word[0:1])

In [ ]:
len(df_word[9])
df_word[9]

['fockers',
 'fuel',
 'festive',
 'film',
 'chart',
 'comedy',
 'meet',
 'fockers',
 'topped',
 'festive',
 'box',
 'office',
 'north',
 'america',
 'setting',
 'new',
 'record',
 'christmas',
 'day',
 '.',
 'sequel',
 'took',
 '$',
 '44.7m',
 '(',
 '£23.2m',
 ')',
 '24',
 '26',
 'december',
 'according',
 'studio',
 'estimates',
 '.',
 'took',
 '$',
 '19.1m',
 '(',
 '£9.9m',
 ')',
 'christmas',
 'day',
 'alone',
 'highest',
 'takings',
 'day',
 'box',
 'office',
 'history',
 '.',
 'meet',
 'fockers',
 'sequel',
 'ben',
 'stiller',
 'comedy',
 'meet',
 'parents',
 'also',
 'starring',
 'robert',
 'de',
 'niro',
 'blythe',
 'danner',
 'dustin',
 'hoffman',
 'barbra',
 'streisand',
 '.',
 'despite',
 'success',
 'meet',
 'fockers',
 'takings',
 '26.5',
 '%',
 '2003',
 'figures',
 '-',
 'blamed',
 'christmas',
 'falling',
 'weekend',
 'year',
 '.',
 'christmas',
 'falls',
 'weekend',
 'bad',
 'business',
 'said',
 'paul',
 'dergarabedian',
 'president',
 'exhibitor',
 'relations',
 'compiles',
 'box',
 'office',
 'statistics',
 '.',
 'weekend',
 'top',
 '12',
 'films',
 'took',
 'estimated',
 '$',
 '121.9m',
 '(',
 '£63.3m',
 ')',
 'compared',
 '$',
 '165.8m',
 '(',
 '£86.1m',
 ')',
 'last',
 'year',
 'third',
 'lord',
 'rings',
 'film',
 'dominated',
 'box',
 'office',
 '.',
 'meet',
 'fockers',
 'knocked',
 'last',
 'week',
 'top',
 'film',
 'lemony',
 'snicket',
 'series',
 'unfortunate',
 'events',
 'third',
 'place',
 '$',
 '12.5m',
 '(',
 '£6.5m',
 ')',
 '.',
 'comedy',
 'fat',
 'albert',
 '-',
 'co-written',
 'bill',
 'cosby',
 '-',
 'entered',
 'chart',
 'second',
 'place',
 'opening',
 'christmas',
 'day',
 'taking',
 '$',
 '12.7m',
 '(',
 '£6.6m',
 ')',
 '.',
 'aviator',
 'starring',
 'leonardo',
 'dicaprio',
 'howard',
 'hughes',
 'took',
 '$',
 '9.4m',
 'expanding',
 '40',
 '1',
 '796',
 'cinemas',
 'christmas',
 'day',
 '.']

In [ ]:
# Removing Punctuations
import string

# punctuations
punctuations=list(string.punctuation)

#print(df_word[0:1]);
for i in range(len(df_word)):
    temp = []
    for j in df_word[i]:
        if j not in punctuations:
            temp.append(j)
    #print(temp)
    df_word[i] = temp.copy()

#print(df_word[0:1])

In [ ]:
len(df_word[9])
df_word[9]

['fockers',
 'fuel',
 'festive',
 'film',
 'chart',
 'comedy',
 'meet',
 'fockers',
 'topped',
 'festive',
 'box',
 'office',
 'north',
 'america',
 'setting',
 'new',
 'record',
 'christmas',
 'day',
 'sequel',
 'took',
 '44.7m',
 '£23.2m',
 '24',
 '26',
 'december',
 'according',
 'studio',
 'estimates',
 'took',
 '19.1m',
 '£9.9m',
 'christmas',
 'day',
 'alone',
 'highest',
 'takings',
 'day',
 'box',
 'office',
 'history',
 'meet',
 'fockers',
 'sequel',
 'ben',
 'stiller',
 'comedy',
 'meet',
 'parents',
 'also',
 'starring',
 'robert',
 'de',
 'niro',
 'blythe',
 'danner',
 'dustin',
 'hoffman',
 'barbra',
 'streisand',
 'despite',
 'success',
 'meet',
 'fockers',
 'takings',
 '26.5',
 '2003',
 'figures',
 'blamed',
 'christmas',
 'falling',
 'weekend',
 'year',
 'christmas',
 'falls',
 'weekend',
 'bad',
 'business',
 'said',
 'paul',
 'dergarabedian',
 'president',
 'exhibitor',
 'relations',
 'compiles',
 'box',
 'office',
 'statistics',
 'weekend',
 'top',
 '12',
 'films',
 'took',
 'estimated',
 '121.9m',
 '£63.3m',
 'compared',
 '165.8m',
 '£86.1m',
 'last',
 'year',
 'third',
 'lord',
 'rings',
 'film',
 'dominated',
 'box',
 'office',
 'meet',
 'fockers',
 'knocked',
 'last',
 'week',
 'top',
 'film',
 'lemony',
 'snicket',
 'series',
 'unfortunate',
 'events',
 'third',
 'place',
 '12.5m',
 '£6.5m',
 'comedy',
 'fat',
 'albert',
 'co-written',
 'bill',
 'cosby',
 'entered',
 'chart',
 'second',
 'place',
 'opening',
 'christmas',
 'day',
 'taking',
 '12.7m',
 '£6.6m',
 'aviator',
 'starring',
 'leonardo',
 'dicaprio',
 'howard',
 'hughes',
 'took',
 '9.4m',
 'expanding',
 '40',
 '1',
 '796',
 'cinemas',
 'christmas',
 'day']

In [ ]:
# Here we achieve the Vocabulary, or wordset, (1)
wordset = []
for i in range(len(df_word)):
    wordset =  np.union1d(wordset,df_word[i])
len(wordset)

6349

In [ ]:
# Function to convert each of the review to a dictionary where the keys are the words in the vocabulary,  (2)
# and the key's(word's) value is the count of that word(key) in the corresponding review
def calculateBW(wordset,doc):
  tf = dict.fromkeys(wordset,0)
  for word in doc:
      tf[word]=doc.count(word)
  return tf

In [ ]:
bw ={}
for i in range(len(df_word)):
    bw[i] = calculateBW(wordset,df_word[i])


#for i in range(len(bw)):

bow = pd.DataFrame(bw)
bow = bow.T

bow


#bow.to_csv('BoW.csv')

,--,-top,...,0-30,0.2,0.27,0.4,000,000-acre,000-seater,...,£63.3m,£6m,£7m,£8.7bn,£85,£86.1m,£89m,£9.9m,£93.6bn,£99
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0,0,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
bow.head()

,--,-top,...,0-30,0.2,0.27,0.4,000,000-acre,000-seater,...,£63.3m,£6m,£7m,£8.7bn,£85,£86.1m,£89m,£9.9m,£93.6bn,£99
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [ ]:
import numpy as np
senta= np.array(bow.iloc[0])
sentb= np.array(bow.iloc[1])
dot_product = np.dot(senta, sentb)

# Calculate the Euclidean norms
norm_senta = np.linalg.norm(senta)
norm_sentb = np.linalg.norm(sentb)

# Calculate the cosine similarity
cosine_similarity = dot_product / (norm_senta * norm_sentb)

print(cosine_similarity)

0.09584971656529236

In [ ]:
similarity = []
for i in range(len(bow)):
  row=[]
  for j in range(len(bow)):
    senta = np.array(bow.iloc[i])
    sentb = np.array(bow.iloc[j])
    dot_product = np.dot(senta, sentb)

    norm_senta = np.linalg.norm(senta)
    norm_sentb = np.linalg.norm(sentb)
    cosine_similarity = dot_product / (norm_senta * norm_sentb)
    row.append(cosine_similarity)
  similarity.append(row)

In [ ]:
short_similarity = [row[:5] for row in similarity[:5]]
for row in short_similarity:
  formatted_row = [f"{value:.{3}f}" for value in row]
  print(" ".join(formatted_row))

1.000 0.096 0.072 0.109 0.176
0.096 1.000 0.193 0.134 0.072
0.072 0.193 1.000 0.189 0.059
0.109 0.134 0.189 1.000 0.062
0.176 0.072 0.059 0.062 1.000

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report

train_data = pd.read_csv('/content/drive/MyDrive/S7/Text Mining/Exp 3/BBC News Train.csv')
test_data = pd.read_csv('/content/drive/MyDrive/S7/Text Mining/Exp 3/BBC News Test.csv')

vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(train_data['Text'])
X_test = vectorizer.transform(test_data['Text'])
y_train = train_data['Category']
y_test = test_data['Category']

nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

nb_predictions = nb_model.predict(X_test)
print("Naïve Bayes Predicted Categories:")
print(nb_predictions)

svm_model = SVC(kernel='linear')
svm_model.fit(X_train, y_train)

svm_predictions = svm_model.predict(X_test)
print("\nSupport Vector Machines Predicted Categories:")
print(svm_predictions)

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

knn_predictions = knn_model.predict(X_test)
print("\nK-Nearest Neighbor Predicted Categories:")
print(knn_predictions)

print("\nClassification Report for Naïve Bayes:")
print(classification_report(y_test, nb_predictions))

print("\nClassification Report for Support Vector Machines:")
print(classification_report(y_test, svm_predictions))

print("\nClassification Report for K-Nearest Neighbor:")
print(classification_report(y_test, knn_predictions))

Naïve Bayes Predicted Categories:
['sport' 'tech' 'sport' 'business' 'sport' 'sport' 'politics' 'sport'
 'entertainment' 'business' 'business' 'tech' 'sport' 'tech'
 'entertainment' 'sport' 'politics' 'tech' 'entertainment' 'sport'
 'business' 'politics' 'sport' 'business' 'politics' 'sport' 'business'
 'sport' 'sport' 'business' 'politics' 'tech' 'business' 'business'
 'sport' 'sport' 'sport' 'business' 'entertainment' 'business' 'tech'
 'politics' 'entertainment' 'tech' 'sport' 'tech' 'entertainment'
 'business' 'politics' 'business' 'politics' 'business' 'business'
 'business' 'tech' 'politics' 'tech' 'sport' 'sport' 'tech' 'sport'
 'entertainment' 'tech' 'politics' 'business' 'sport' 'sport' 'tech'
 'sport' 'sport' 'tech' 'sport' 'business' 'politics' 'tech' 'sport'
 'tech' 'tech' 'tech' 'entertainment' 'politics' 'sport' 'entertainment'
 'sport' 'business' 'entertainment' 'business' 'entertainment' 'business'
 'tech' 'business' 'sport' 'sport' 'tech' 'sport' 'sport' 'sport' 'sport'
 'sport' 'sport']

Support Vector Machines Predicted Categories:
['sport' 'tech' 'sport' 'business' 'sport' 'sport' 'politics' 'sport'
 'entertainment' 'business' 'business' 'tech' 'politics' 'tech'
 'entertainment' 'sport' 'politics' 'tech' 'entertainment' 'entertainment'
 'business' 'politics' 'sport' 'business' 'politics' 'sport' 'business'
 'sport' 'sport' 'business' 'politics' 'tech' 'business' 'business'
 'sport' 'sport' 'sport' 'business' 'entertainment' 'entertainment' 'tech'
 'politics' 'entertainment' 'tech' 'sport' 'tech' 'entertainment'
 'business' 'politics' 'business' 'politics' 'business' 'business'
 'business' 'tech' 'politics' 'tech' 'tech' 'sport' 'tech' 'sport'
 'entertainment' 'tech' 'politics' 'business' 'entertainment' 'sport'
 'tech' 'sport' 'sport' 'tech' 'sport' 'business' 'politics' 'tech'
 'sport' 'tech' 'tech' 'tech' 'entertainment' 'politics' 'sport'
 'entertainment' 'entertainment' 'business' 'entertainment' 'business'
 'entertainment' 'business' 'tech' 'business' 'tech' 'sport' 'tech'
 'sport' 'sport' 'sport' 'sport' 'sport' 'sport']

K-Nearest Neighbor Predicted Categories:
['sport' 'tech' 'sport' 'entertainment' 'sport' 'sport' 'politics'
 'entertainment' 'entertainment' 'politics' 'business' 'tech' 'politics'
 'tech' 'entertainment' 'entertainment' 'politics' 'tech' 'entertainment'
 'entertainment' 'business' 'politics' 'sport' 'business' 'politics'
 'sport' 'business' 'sport' 'sport' 'business' 'politics' 'tech'
 'business' 'business' 'sport' 'sport' 'sport' 'business' 'entertainment'
 'entertainment' 'business' 'politics' 'entertainment' 'tech' 'sport'
 'tech' 'entertainment' 'business' 'politics' 'business' 'politics'
 'business' 'business' 'business' 'tech' 'politics' 'tech' 'tech' 'sport'
 'tech' 'sport' 'entertainment' 'tech' 'politics' 'entertainment'
 'entertainment' 'sport' 'tech' 'sport' 'sport' 'tech' 'sport' 'business'
 'politics' 'tech' 'sport' 'tech' 'tech' 'tech' 'entertainment' 'politics'
 'sport' 'entertainment' 'entertainment' 'business' 'entertainment'
 'business' 'entertainment' 'entertainment' 'tech' 'business'
 'entertainment' 'entertainment' 'tech' 'sport' 'sport' 'sport' 'sport'
 'sport' 'sport']

Classification Report for Naïve Bayes:
               precision    recall  f1-score   support

     business       0.23      0.25      0.24        20
entertainment       0.27      0.15      0.19        20
     politics       0.08      0.05      0.06        20
        sport       0.26      0.45      0.33        20
         tech       0.25      0.25      0.25        20

     accuracy                           0.23       100
    macro avg       0.22      0.23      0.21       100
 weighted avg       0.22      0.23      0.21       100


Classification Report for Support Vector Machines:
               precision    recall  f1-score   support

     business       0.24      0.25      0.24        20
entertainment       0.27      0.20      0.23        20
     politics       0.08      0.05      0.06        20
        sport       0.28      0.40      0.33        20
         tech       0.27      0.30      0.29        20

     accuracy                           0.24       100
    macro avg       0.23      0.24      0.23       100
 weighted avg       0.23      0.24      0.23       100


Classification Report for K-Nearest Neighbor:
               precision    recall  f1-score   support

     business       0.28      0.25      0.26        20
entertainment       0.27      0.30      0.29        20
     politics       0.14      0.10      0.12        20
        sport       0.27      0.35      0.30        20
         tech       0.25      0.25      0.25        20

     accuracy                           0.25       100
    macro avg       0.24      0.25      0.24       100
 weighted avg       0.24      0.25      0.24       100

In [ ]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

def plot_model_confusion_matrix(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix for ",model_name)
    print(cm)

plot_model_confusion_matrix(nb_model, X_test, y_test, 'Naïve Bayes')

plot_model_confusion_matrix(svm_model, X_test, y_test, 'Support Vector Machines')

plot_model_confusion_matrix(knn_model, X_test, y_test, 'K-Nearest Neighbor')

Confusion Matrix for  Naïve Bayes
[[5 3 0 8 4]
 [5 3 3 5 4]
 [6 2 1 7 4]
 [3 1 4 9 3]
 [3 2 4 6 5]]
Confusion Matrix for  Support Vector Machines
[[5 3 1 6 5]
 [5 4 3 4 4]
 [5 4 1 6 4]
 [3 2 4 8 3]
 [3 2 4 5 6]]
Confusion Matrix for  K-Nearest Neighbor
[[5 5 1 4 5]
 [3 6 3 4 4]
 [3 5 2 6 4]
 [4 3 4 7 2]
 [3 3 4 5 5]]

In [ ]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)